config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'datasets#index'

  resources :datasets, only: %i(index edit show) do
    get :download

    get :not_found, on: :collection
    get :search, on: :collection

    post :clone

    member do
      get(
        'files/:interface_element_key/*file_key',
        to: 'datasets#git_file_info',
        format: false,
        as: :git_file_info
      )
    end

    resources :commits, only: %i(create) do
      post :dataset_edits, on: :collection
    end
  end

  post :charts, to: "charts#data"

  namespace :api do
    namespace :v1 do
      resources :exports, only: :show
    end
  end

  put '/set_locale(/:locale)' => 'pages#set_new_locale', as: :set_locale
  get '/introduction' => 'pages#introduction'
end

app/models/commit.rb
class Commit < ApplicationRecord
  belongs_to :dataset
  belongs_to :user

  has_many :dataset_edits, inverse_of: :commit

  accepts_nested_attributes_for :dataset_edits, reject_if: :reject_edits

  validates_presence_of :message

  private

  def reject_edits(attributes)
    attributes['value'].blank?
  end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  layout false
  format 'js'

  before_action :authenticate_user!
  before_action :find_dataset
  before_action :find_clones, only: %i(dataset_edits create)

  # GET new
  def new
    @dataset_edit_form = DatasetEditForm.new(
      @dataset.editable_attributes.as_json.merge(country: @dataset.country)
    )
  end

  # POST dataset_edits
  def dataset_edits
    authorize @dataset, :update?

    @dataset_edit_form = DatasetEditForm.new(
      dataset_edit_params.to_h.merge(country: @dataset.country)
    )
    @commit = @dataset_edit_form.submit(@dataset)
  end

  # POST create
  def create
    @commit = current_user.commits.new(commit_params)

    if @commit.save
      @dataset_edit_form = DatasetEditForm.new(
        @dataset.editable_attributes.as_json.merge(country: @dataset.country)
      )

      flash.now[:success] = I18n.t(
        'dataset_edits.success',
        dataset: @dataset.name
      )
    end
  end

  private

  def dataset_edit_params
    params
      .require(:dataset_edit_form)
      .permit(:dataset_id,
        *EditableAttributesCollection.items.map(&:key)
      )
      .reject { |_, val| val.blank? }
  end

  def commit_params
    params
      .require(:change)
      .permit(:message, :dataset_id, dataset_edits_attributes: [:key, :value])
  end

  def find_clones
    @dataset_clones = policy_scope(Dataset).clones(@dataset, current_user)
  end
end

app/views/commits/_form.slim
.heading
  h2 title= "Dataset: #{dataset.id}, GeoID: #{dataset.geo_id}"
    = dataset.name

  .dataset-attribution
    = I18n.t("user.created_by", group: dataset.creator)

- if @dataset_edit_form.errors.any?
  .errors
    - @dataset_edit_form.errors.full_messages.each do |message|
      .error.notice= message

= render 'shared/flash', flash: flash

.hidden
  = form_tag dataset_download_path(dataset), method: :get, class: 'download-dataset' do
    .hidden

  = form_tag dataset_clone_path(dataset, format: :js), remote: true, class: 'clone-dataset' do
    .hidden

= form_for @dataset_edit_form, url: dataset_edits_dataset_commits_path(dataset), remote: true, html: { class: "dataset_editor" } do |form|
  = form.hidden_field :dataset_id, value: dataset.id
  = form.hidden_field :group, value: dataset.group

  .wrapper data-tab-key='main'
    .content.tab#input data-tab="#input"
      .nav#input-nav data-key='input'
        ul.tab-nav
          - menu_structure.each_pair do |group, subgroups|
            li.tab
              = link_to I18n.t("datasets.groups.#{ group }"), "##{ group }", data: { group: group }

              - if subgroups
                ul.sub-nav id=group
                  - subgroups.each do |subgroup|
                    li.tab
                      = link_to "##{ subgroup }", data: { group: group } do
                        | &#8627
                        | &nbsp;
                        = I18n.t("datasets.subgroups.#{ group }.#{ subgroup }")

      .attributes data-tab-key='input'
        .edits
          = render InterfaceElement.all, dataset: dataset, form: form

      .clear

      .overview-edits
        .apply.no-changes
          - if policy(@dataset).clone?
            = button_tag class: 'button clone-dataset', type: 'button' do
              = I18n.t('datasets.commit.clone')

          - if policy(@dataset).download?
            = button_tag class: 'button download-dataset', type: 'button', disabled: download_button_disabled?(dataset) do
              = I18n.t('datasets.commit.download')
              | &nbsp;
              i.fa.fa-download

          .switch-dataset
            - if @dataset_clones.size > 1
              = select_tag "datasets", version_options

          .clear

        .apply.changes
          = button_tag type: 'submit', class: 'button' do
            = I18n.t('datasets.commit.save')
            = image_tag 'wait.gif', class: 'wait'

          .clear

    .clear

    .content.tab#overview data-tab="#overview"
      .group
        .overview
          .analyzes

app/views/commits/create.js.slim
| $('#dataset-overlay .content').html("
- if @commit.valid?
  = j render("commits/form", dataset: @dataset, commit: Commit.new)
- else
  = j render("dataset_edits/form", dataset: @dataset, commit: @commit)
| ");
| DatasetInterface.enable("#{ @dataset.id }");
| $(".content.tab#input").show();

app/views/commits/dataset_edits.js.slim
| $('#dataset-overlay .content').html("
- if @dataset_edit_form.errors.any?
  = j render("commits/form", dataset: @dataset, commit: @commit)
- else
  = j render("dataset_edits/form", dataset: @dataset)
| ");

- if @dataset_edit_form.errors.any?
  | $('#dataset-overlay, .content.tab#input').show();
  | $('.content-map .container #search-bar-holder').hide();
  | DatasetInterface.enable("#{ @dataset.id }");
- else
  | FileUpload.setFields();
  | CommitForm.convertValues();