config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'datasets#index'

  resources :datasets, only: %i(index edit show) do
    get :download

    get :not_found, on: :collection
    get :search, on: :collection

    post :clone

    member do
      get(
        'files/:interface_element_key/*file_key',
        to: 'datasets#git_file_info',
        format: false,
        as: :git_file_info
      )
    end

    resources :commits, only: %i(create) do
      post :dataset_edits, on: :collection
    end
  end

  post :charts, to: "charts#data"

  namespace :api do
    namespace :v1 do
      resources :exports, only: :show
    end
  end

  put '/set_locale(/:locale)' => 'pages#set_new_locale', as: :set_locale
  get '/introduction' => 'pages#introduction'
end

app/models/dataset_edit.rb
class DatasetEdit < ApplicationRecord
  belongs_to :commit

  validates_presence_of :key
  validates_presence_of :value
  validate :validate_attribute_allowed

  def self.sorted
    order('`created_at` DESC')
  end

  def user
    commit.user
  end

  def creator
    user.group ? user.group.key.humanize : user.name
  end

  def as_json(*)
    super.slice('key', 'value')
  end

  private

  def validate_attribute_allowed
    return if key.blank? || value.blank? || commit.nil? || commit.dataset.nil?

    item = EditableAttributesCollection.item(key)

    unless item
      errors.add(:key, 'does not have a matching interface element')
      return
    end

    # Verifies that the dataset allows this field to be edited.
    unless item.editable?(commit.dataset)
      errors.add(:value, 'is not allowed to be changed (update the energy balance CSV instead)')
    end
  end
end

app/views/dataset_edits/_form.slim
.heading
  h5 title= @dataset.geo_id
    = @dataset.name.humanize

= render 'shared/flash', flash: flash

.errors
  - @commit.errors.full_messages.each do |message|
    .error.notice= message

= form_for [dataset, @commit], as: :change, url: dataset_commits_path(dataset), remote: true do |form|
  .edit-form
    .content
      .attributes-changed
        strong= I18n.t('dataset_edits.changed_attributes')

        - @commit.dataset_edits.each do |edit|
          .edit
            span.arrow>
              | &rarr;
            span.key>
              = I18n.t("activemodel.attributes.dataset_edit_form.#{ edit.key }", default: edit.key.humanize).html_safe

            span.to>
              = I18n.t('to')
            span.val data= conversions_for(edit.key)
              = edit.value

            span.unit
              | &nbsp;
              = I18n.t("units.#{ edit.key }.to", default: default_unit_for(edit.key)).html_safe

        hr

        = form.hidden_field :dataset_id, value: dataset.id
        = form.fields_for(:dataset_edits) do |d|
          = d.hidden_field :key, value: d.object.key
          = d.hidden_field :value, value: d.object.value

        .field
          = form.label :message, I18n.t('dataset_edits.reason_changes')
          = form.text_area :message, maxlength: 500

      .overview-edits
        .apply
          = form.submit I18n.t('dataset_edits.form.save')
          = link_to I18n.t('dataset_edits.form.cancel'), edit_dataset_path(dataset, format: :js), remote: true, class: "button danger"

app/views/dataset_edits/edit.slim
.edit-form
  .errors
    - @commit.errors.full_messages.each do |message|
      .error.notice= message

  .wrapper
    = form_for @commit, as: :change, url: dataset_dataset_edit_path(@dataset.area, @dataset_edit.key), method: :patch do |form|
      = form.hidden_field :dataset_area, value: @dataset.area

      .field
        = form.fields_for(:dataset_edits) do |d|
          = d.label @dataset_edit.key
          = d.hidden_field :key, value: @dataset_edit.key

          = d.text_field :value, placeholder: dataset_value_for(@dataset_edit.key).to_s
          span.unit= unit_for(@dataset_edit)

      .field
        = form.label :message
        = form.text_area :message, maxlength: 500

      = form.fields_for(:source) do |s|
        .field.file
          = s.file_field :source_file
          = s.label :source_file do
            => I18n.t("datasets.attributes.source_file")
            i.fa.fa-upload
            span= filename_for_source

      = form.submit "Save"
      span.or or
      = link_to "Cancel", dataset_path(@dataset.area), class: "button cancel"

    .history
      = render 'history'