config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'datasets#index'

  resources :datasets, only: %i(index edit show) do
    get :download

    get :not_found, on: :collection
    get :search, on: :collection

    post :clone

    member do
      get(
        'files/:interface_element_key/*file_key',
        to: 'datasets#git_file_info',
        format: false,
        as: :git_file_info
      )
    end

    resources :commits, only: %i(create) do
      post :dataset_edits, on: :collection
    end
  end

  post :charts, to: "charts#data"

  namespace :api do
    namespace :v1 do
      resources :exports, only: :show
    end
  end

  put '/set_locale(/:locale)' => 'pages#set_new_locale', as: :set_locale
  get '/introduction' => 'pages#introduction'
end

app/views/layouts/_header.slim
.header
  .title
    a href=root_path
      h2 Energy Transition Model
      h1 Dataset Manager

  .right
    .info
      span.fa.fa-info
      = link_to t('information'), intro_path
    .dropdown
      .lang-select
        span.fa.fa-globe
        = t('current_language')
        span.fa.fa-caret-down
      ul.dropdown-menu
        li
          = link_to 'English', set_locale_path(locale: 'en'), method: :put, class: 'dropdown-item'
        li
           = link_to 'Nederlands', set_locale_path(locale: 'nl'), method: :put, class: 'dropdown-item'

    - if current_user
      .current-user
        span.name.button
          = current_user.name
        .log-out
          = link_to I18n.t('user.sign_out'), destroy_user_session_path, class: 'button', method: :delete
    - else
      .current-user
        = link_to I18n.t('devise.log_in'), new_user_session_path, class: 'button'

app/views/layouts/_hidden.slim
.hidden
  .mapbox-api-key
    = Rails.application.secrets.mapbox_api_key

  .layers
    = LAYERS.to_json

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title= I18n.t("application")
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .colored-header
      .container
        = render 'layouts/header'

    .container
      .content
        = yield

      = render 'layouts/hidden'

app/views/layouts/map.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title= I18n.t("application")
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    - Dir[Rails.root.join("**", "*.hdb")].each do |hdb_file|
      script id=File.basename(hdb_file, ".hdb") type="text/x-handlebars-template"
        = File.read(hdb_file).html_safe

  body
    .colored-header
      .container
        = render 'layouts/header'

    .content-map
      = yield

    = render 'layouts/hidden'